<?php

namespace Runalyze\Calculation\Scale;

/**
 * Generated by hand
 */
class TwoPartPercentalTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var TwoPartPercental
	 */
	protected $object;

	protected function setUp() {
		$this->object = new TwoPartPercental();
	}

	protected function tearDown() {
	}

	public function testNoTransformation() {
		$this->assertEquals(   0, $this->object->transform(-10) );
		$this->assertEquals(  26, $this->object->transform( 26) );
		$this->assertEquals(  50, $this->object->transform( 50) );
		$this->assertEquals( 100, $this->object->transform(120) );
	}

	public function testSimpleScale() {
		$this->object->setMinimum(1);
		$this->object->setInflectionPoint(2);
		$this->object->setMaximum(10);

		$this->assertEquals(   0, $this->object->transform(1) );
		$this->assertEquals(   5, $this->object->transform(1.1) );
		$this->assertEquals(  25, $this->object->transform(1.5) );
		$this->assertEquals(  50, $this->object->transform(2.0) );
		$this->assertEquals(  50, $this->object->transform(2.0) );
		$this->assertEquals(  56, $this->object->transform(3.0), '', 0.5 );
		$this->assertEquals(  75, $this->object->transform(6.0) );
	}
}
