<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-07 at 17:50:49.
 */
class ParserHRMSingleTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ParserHRMSingle
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() { }

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() { }

	public function testVerySimple() {
		$String = '[Params]
Version=106
Monitor=0
SMode=11000000
Date=20120104
StartTime=05:35:03.0
Length=00:59:36.4

[IntTimes]
00:06:57.9	136	0	132	162
0	0	0	0	0	0
0	0	0	0	0
0	0	0	0	0	0
0	0	0	0	0	0
00:14:03.5	140	0	138	141
0	0	0	0	0	0
0	0	0	0	0
[HRData]
100	0	0
120	0	0';

		$Parser = new ParserHRMSingle($String);
		$Parser->parse();

		$this->assertFalse( $Parser->failed() );
		$this->assertEquals( mktime(5, 35, 3, 1, 4, 2012), $Parser->object()->getTimestamp() );
		$this->assertEquals( 59*60 + 36.4, $Parser->object()->getTimeInSeconds() );
		$this->assertEquals( 110, $Parser->object()->getPulseAvg() );
		$this->assertEquals( 120, $Parser->object()->getPulseMax() );
		$this->assertEquals( array(100,120), $Parser->object()->getArrayHeartrate() );
		$this->assertEquals( '0.00|6:58-0.00|7:06', $Parser->object()->Splits()->asString() );
	}

}
