<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-07 at 17:50:49.
 */
class ParserPWXSingleTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ParserTCXSingle
	 */
	protected $object;

	/**
	 * @expectedException \Runalyze\Import\Exception\ParserException
	 */
	public function testWrongXML() {
		$XML = simplexml_load_string('<test>abc</test>');
		$Parser = new ParserPWXSingle('', $XML);
		$Parser->parse();
	}

}
