<?php

namespace Runalyze\Model\Sport;

/**
 * Generated by hand
 */
class EntityTest extends \PHPUnit_Framework_TestCase {

	public function testSimpleObject() {
		$Sport = new Entity(array(
			Entity::NAME => 'Sport name',
			Entity::SHORT => 0,
			Entity::CALORIES_PER_HOUR => 700,
			Entity::HR_AVG => 140,
			Entity::HAS_DISTANCES => 1,
			Entity::PACE_UNIT => 'foo',
			Entity::HAS_POWER => 0,
			Entity::IS_OUTSIDE => 1
		));

		$this->assertEquals('Sport name', $Sport->name());
		$this->assertEquals(700, $Sport->caloriesPerHour());
		$this->assertEquals(140, $Sport->avgHR());
		$this->assertEquals('foo', $Sport->paceUnitEnum());
		$this->assertTrue($Sport->hasDistances());
		$this->assertTrue($Sport->isOutside());

		$this->assertFalse($Sport->usesShortDisplay());
		$this->assertFalse($Sport->hasPower());
	}

	/**
	 * @see https://github.com/Runalyze/Runalyze/issues/1585
	 */
	public function testPaceUnitForEmptySport() {
		$Sport = new Entity(array());
		$Sport->paceUnit();
	}

}
