<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-15 at 19:50:44.
 */
class ConfigurationHandleTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ConfigurationHandle
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ConfigurationHandle('key', new ParameterInt(42));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ConfigurationHandle::key
	 */
	public function testKey() {
		$this->assertEquals('key', $this->object->key());
	}

	/**
	 * @covers ConfigurationHandle::object
	 */
	public function testObject() {
		$this->object->object()->set(1337);
		$this->assertEquals(1337, $this->object->object()->value());
	}

	/**
	 * @covers ConfigurationHandle::value
	 */
	public function testValue() {
		$this->assertEquals(42, $this->object->value());
	}

}
