<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-17 at 16:05:13.
 */
class WeatherOpenweathermapTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var WeatherOpenweathermap
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new WeatherOpenweathermap;

		if (!defined('CONF_PLZ'))
			define('CONF_PLZ', 'Kaiserslautern, de');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	public function testEmptyValues() {
		$this->assertNull( $this->object->getTemperature() );
		$this->assertEquals( $this->object->getConditionAsString(), '' );
	}

	/**
	 * @covers WeatherOpenweathermap::loadForecast
	 * @covers WeatherOpenweathermap::setFromJSON
	 * @covers WeatherOpenweathermap::getConditionAsString
	 * @covers WeatherOpenweathermap::getTemperature
	 */
	public function testLoadForecast() {
		$this->object->setFromJSON('
			{"message":"","cod":"200","type":"base-country","calctime":"","units":"metric","count":1,
				"list":[{
					"id":2894003,"coord":{"lat":49.450001,"lon":7.75},"name":"Kaiserslautern",
					"main":{"temp":4.21,"pressure":998,"humidity":86,"temp_min":2.78,"temp_max":5},
					"dt":1363532773,"date":"2013-03-17 15:06:13","wind":{"speed":3.1,"deg":180},"clouds":{"all":90},
					"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],
					"sys":{"country":"DE","population":98732},"url":"http:\/\/openweathermap.org\/city\/2894003"
				}]
			}');

		$this->assertEquals($this->object->getConditionAsString(), 'rainy');
		$this->assertEquals($this->object->getTemperature(), 4);
	}
}
