<?php

namespace Runalyze\Model\Tag;

/**
 * Generated by hand
 */
class ObjectTest extends \PHPUnit_Framework_TestCase {

	public function testSimpleObject() {
		$Tag = new Object(array(
			Object::TAG => 'Tag Test'
		));

		$this->assertEquals('Tag Test', $Tag->tag());
	}

}
