imports:
    - { resource: config_test.yml }

parameters:
  database_prefix: runalyze_test_empty_

doctrine:
  dbal:
    connections:
      default:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        options: {1002: "SET time_zone = '+00:00'"}
        mapping_types:
          enum:   string
