imports:
    - { resource: config.yml }

parameters:
  database_host: 127.0.0.1
  database_prefix: runalyze_test_
  database_port: 3306
  database_name: runalyze_test
  database_user: root
  database_password:

liip_functional_test:
  cache_sqlite_db: true
  authentication:
    username: "default"
    password: "defaultPassword"

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
    name: MOCKSESSID

security:
  firewalls:
    default:
      http_basic: ~

doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: pdo_sqlite
        path: %kernel.cache_dir%/test.db
