<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-15 at 21:22:07.
 */
class ActivityRoutePrivacyTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ActivityRoutePrivacy
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ActivityRoutePrivacy;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ActivityRoutePrivacy::showNever
	 * @covers ActivityRoutePrivacy::showRace
	 * @covers ActivityRoutePrivacy::showRaceAndLongrun
	 * @covers ActivityRoutePrivacy::showAlways
	 */
	public function testValues() {
		$this->assertEquals( true, $this->object->showAlways() );
		$this->assertEquals( false, $this->object->showNever() );
		$this->assertEquals( false, $this->object->showRace() );
		$this->assertEquals( false, $this->object->showRaceAndLongrun() );

		$this->object->set( ActivityRoutePrivacy::NEVER );
		$this->assertEquals( false, $this->object->showAlways() );
		$this->assertEquals( true, $this->object->showNever() );
		$this->assertEquals( false, $this->object->showRace() );
		$this->assertEquals( false, $this->object->showRaceAndLongrun() );

		$this->object->set( ActivityRoutePrivacy::RACE );
		$this->assertEquals( false, $this->object->showAlways() );
		$this->assertEquals( false, $this->object->showNever() );
		$this->assertEquals( true, $this->object->showRace() );
		$this->assertEquals( false, $this->object->showRaceAndLongrun() );

		$this->object->set( ActivityRoutePrivacy::RACE_LONGRUN );
		$this->assertEquals( false, $this->object->showAlways() );
		$this->assertEquals( false, $this->object->showNever() );
		$this->assertEquals( false, $this->object->showRace() );
		$this->assertEquals( true, $this->object->showRaceAndLongrun() );
	}

}
