<?php

namespace Runalyze\Data\Weather;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-27 at 18:55:20.
 */
class ConditionTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Condition
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Condition(0);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Runalyze\Data\Weather\Condition::completeList
	 * @covers Runalyze\Data\Weather\Condition::set
	 * @covers Runalyze\Data\Weather\Condition::id
	 * @covers Runalyze\Data\Weather\Condition::icon
	 * @covers Runalyze\Data\Weather\Condition::string
	 */
	public function testConditions() {
		foreach (Condition::completeList() as $id) {
			$this->object->set($id);

			$this->assertEquals($id, $this->object->id());
			$this->assertInstanceOf('\Runalyze\View\Icon', $this->object->icon());
			$this->assertNotEmpty($this->object->string());
		}
	}

	public function testUnknown() {
		$this->object->set(Condition::UNKNOWN);

		$this->assertTrue($this->object->isUnknown());
	}

}
