<?php

namespace Runalyze\Data\Weather;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-02 at 14:44:59.
 */
class ForecastTest extends \PHPUnit_Framework_TestCase {
	public function testEmptyLocation() {
		$Forecast = new Forecast(new Openweathermap, new Location);
		$object = $Forecast->object();

		$this->assertTrue( $object->isEmpty() );
	}

	public function testLocationByName() {
		$Location = new Location();
		$Location->setLocationName('Berlin, de');

		$Forecast = new Forecast(new Openweathermap, $Location);
		$object = $Forecast->object();

		$this->assertFalse( $object->isEmpty() );
	}

	public function testLocationByTime() {
		// Historical data, '< 1 month (list of available cities is limited)'
		// @see http://bugs.openweathermap.org/projects/api/wiki/Api_2_5_history
		// @see http://openweathermap.org/price
		$Location = new Location();
		$Location->setLocationName('Berlin, de');
		$Location->setTimestamp( time() - 28*86500 );

		$Forecast = new Forecast(new Openweathermap, $Location);
		$object = $Forecast->object();

		$this->assertFalse( $object->isEmpty() );
	}

	public function testLocationByPosition() {
		$Location = new Location();
		$Location->setPosition(49.9, 7.77);

		$Forecast = new Forecast(new Openweathermap, $Location);
		$object = $Forecast->object();

		$this->assertFalse( $object->isEmpty() );
	}

}
