<?php

namespace Runalyze\Data\Weather;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-27 at 17:30:48.
 */
class WindSpeedTest extends \PHPUnit_Framework_TestCase {
	public function testIsUnknown() {
		$WindSpeed = new WindSpeed();

		$this->assertTrue($WindSpeed->isUnknown());
		$this->assertEquals(null, $WindSpeed->value());
	}

	public function testIsUnknownWithUnit() {
		$WindSpeed = new WindSpeed(null, Temperature::KELVIN);

		$this->assertTrue($WindSpeed->isUnknown());
		$this->assertEquals(null, $WindSpeed->value());
	}

	public function testMetric() {
		$WindSpeed = new WindSpeed(30);
		$this->assertEquals(30, $WindSpeed->value());
		$this->assertEquals('km/h', $WindSpeed->unit());
		$this->assertFalse($WindSpeed->isUnknown());
	}
	
	public function testImperial() {
		$WindSpeed = new WindSpeed(30, \Runalyze\Parameter\Application\DistanceUnitSystem::IMPERIAL);
		$this->assertEquals(30, $WindSpeed->value());
		$this->assertEquals('mph', $WindSpeed->unit());
		$this->assertFalse($WindSpeed->isUnknown());
	}


}
