<?php

namespace Runalyze\Data\Weather;

/**
 * Generated by manual
 */
class WindChillFactorTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var WindChillFactor
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new WindChillFactor(new WindSpeed(20), new \Runalyze\Activity\Temperature(10), new \Runalyze\Activity\Pace(5000, 5));
	}

	
	public function testValue() {
		$this->assertEquals('7.1', $this->object->value(), '', 0.1);
	}

}
