<?php

namespace Runalyze\Calculation\Trimp;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-10-11 at 09:00:23.
 */
class DataCollectorTest extends \PHPUnit_Framework_TestCase {

	public function testSingleValueWithoutDuration() {
		$Collector = new DataCollector(
			array(140)
		);

		$this->assertEquals(array(
			140 => 1
		), $Collector->result());
	}

	public function testSingleValueWithDuration() {
		$Collector = new DataCollector(
			array(150),
			array(60)
		);

		$this->assertEquals(array(
			150 => 60
		), $Collector->result());
	}

	public function testArrayWithoutDuration() {
		$Collector = new DataCollector(
			array(140,145,140,150,160,175,190,150,145,140)
		);

		$this->assertEquals(array(
			140 => 3,
			145 => 2,
			150 => 2,
			160 => 1,
			175 => 1,
			190 => 1
		), $Collector->result());
	}

	public function testArrayWithDuration() {
		$Collector = new DataCollector(
			array(140,145,140,150,160,175,190,150,145,140),
			array( 60, 90,100,140,170,190,200,230,290,300)
			
		);

		$this->assertEquals(array(
			140 => 80,
			145 => 90,
			150 => 70,
			160 => 30,
			175 => 20,
			190 => 10
		), $Collector->result());
	}

}
