<?php

namespace Runalyze\Plugin\Tool\DatabaseCleanup;

require_once FRONTEND_PATH.'../plugin/RunalyzePluginTool_DatenbankCleanup/Job.php';
require_once FRONTEND_PATH.'../plugin/RunalyzePluginTool_DatenbankCleanup/JobLoop.php';

use DB;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-12-01 at 21:29:05.
 */
class JobLoopTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var \PDO
	 */
	protected $PDO;

	protected function setUp() {
		$this->PDO = DB::getInstance();
		$this->PDO->exec('TRUNCATE TABLE `runalyze_route`');
		$this->PDO->exec('TRUNCATE TABLE `runalyze_trackdata`');
		$this->PDO->exec('TRUNCATE TABLE `runalyze_training`');

		$_POST = array();
	}
	protected function tearDown() {
		$this->PDO->exec('TRUNCATE TABLE `runalyze_route`');
		$this->PDO->exec('TRUNCATE TABLE `runalyze_trackdata`');
		$this->PDO->exec('TRUNCATE TABLE `runalyze_training`');

		$_POST = array();
	}

	public function testNoLoopForSingleActivity() {
		$this->PDO->exec('INSERT INTO `runalyze_training` (`id`, `distance`, `s`, `pulse_avg`) VALUES (1, 10, 3600, 150)');

		$Loop = new JobLoop;
		$Loop->run();

		$data = $this->PDO->query('SELECT * FROM `runalyze_training` WHERE `id`=1 LIMIT 1')->fetch();
		$this->assertEquals(0, $data['elevation']);
		$this->assertEquals(0, $data['vdot']);
		$this->assertEquals(0, $data['vdot_by_time']);
		$this->assertEquals(0, $data['vdot_with_elevation']);
		$this->assertEquals(0, $data['jd_intensity']);
		$this->assertEquals(0, $data['trimp']);
	}

	public function testCompleteLoopForSingleActivity() {
		$this->PDO->exec('INSERT INTO `runalyze_training` (`id`, `distance`, `s`, `pulse_avg`) VALUES (1, 10, 3600, 150)');

		$_POST = array(
			JobLoop::ELEVATION => 'on',
			JobLoop::ELEVATION_OVERWRITE => 'on',
			JobLoop::VDOT => 'on',
			JobLoop::JD_POINTS => 'on',
			JobLoop::TRIMP => 'on'
		);

		$Loop = new JobLoop;
		$Loop->run();

		$data = $this->PDO->query('SELECT * FROM `runalyze_training` WHERE `id`=1 LIMIT 1')->fetch();
		$this->assertNotEquals(0, $data['vdot']);
		$this->assertNotEquals(0, $data['vdot_by_time']);
		$this->assertNotEquals(0, $data['vdot_with_elevation']);
		$this->assertNotEquals(0, $data['jd_intensity']);
		$this->assertNotEquals(0, $data['trimp']);
	}

}
