<?php

namespace Runalyze\Parameter\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-15 at 20:35:10.
 */
class TemperatureUnitTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var \Runalyze\Parameter\Application\Temperature
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new TemperatureUnit;
	}

	public function testHasTemperature() {

		$this->object->set(TemperatureUnit::CELSIUS );
		$this->assertTrue( $this->object->isCelsius() );
		$this->assertFalse( $this->object->isFahrenheit() );

		$this->object->set( TemperatureUnit::FAHRENHEIT );
		$this->assertFalse( $this->object->isCelsius() );
		$this->assertTrue( $this->object->isFahrenheit() );
	}

}
