<?php

namespace Runalyze\Parameter\Application;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-15 at 20:35:10.
 */
class WeekStartTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var \Runalyze\Parameter\Application\WeekStart
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new WeekStart;
	}

	public function testNoneSet() {
		$this->assertTrue( $this->object->isMonday() );
                $this->assertEquals( 1, $this->object->value() );
		$this->assertFalse( $this->object->isSaturday() );
                $this->assertFalse( $this->object->isSunday() );
        }
        
        public function testMonday() {                
		$this->object->set( WeekStart::MONDAY );
                $this->assertEquals( 1, $this->object->value() );
		$this->assertTrue( $this->object->isMonday() );
		$this->assertFalse( $this->object->isSaturday() );
                $this->assertFalse( $this->object->isSunday() );
        }
        
        public function testSaturday() {
		$this->object->set( WeekStart::SATURDAY );
                $this->assertEquals( 6, $this->object->value() );
		$this->assertFalse( $this->object->isMonday() );
		$this->assertTrue( $this->object->isSaturday() );
                $this->assertFalse( $this->object->isSunday() );
        }
        
        public function testSunday() {
		$this->object->set( WeekStart::SUNDAY );
                $this->assertEquals( 0, $this->object->value() );
		$this->assertFalse( $this->object->isMonday() );
		$this->assertFalse( $this->object->isSaturday() );
                $this->assertTrue( $this->object->isSunday() );
	}
        
        

}
