var f=document.createElement("link");
f.setAttribute("rel", "stylesheet");
f.setAttribute("type", "text/css");
f.setAttribute("href", "//runalyze.com/lib/embedded.css");
document.getElementsByTagName("head")[0].appendChild(f);
var g=document.createElement("link");
g.setAttribute("rel", "stylesheet");
g.setAttribute("type", "text/css");
g.setAttribute("href", "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css");
document.getElementsByTagName("head")[0].appendChild(g);