DELETE FROM `runalyze_conf` WHERE `key`="JS_USE_TOOLTIP";
DELETE FROM `runalyze_conf` WHERE `key`="DESIGN_TOOLBAR_POSITION";
DELETE FROM `runalyze_conf` WHERE `key`="PLUGIN_SHOW_MOVE_LINK";
DELETE FROM `runalyze_conf` WHERE `key`="PLUGIN_SHOW_CONFIG_LINK";
DELETE FROM `runalyze_conf` WHERE `key`="TRAINING_PLOTS_BELOW";