ALTER TABLE `runalyze_dataset` ADD `label` VARCHAR( 100 ) NOT NULL AFTER `name`;

UPDATE `runalyze_dataset` SET `label` = 'Sportart' WHERE `name`="sportid";
UPDATE `runalyze_dataset` SET `label` = 'Trainingstyp' WHERE `name`="typeid";
UPDATE `runalyze_dataset` SET `label` = 'Uhrzeit' WHERE `name`="time";
UPDATE `runalyze_dataset` SET `label` = 'Distanz' WHERE `name`="distance";
UPDATE `runalyze_dataset` SET `label` = 'Dauer' WHERE `name`="s";
UPDATE `runalyze_dataset` SET `label` = 'Pace' WHERE `name`="pace";
UPDATE `runalyze_dataset` SET `label` = 'H&ouml;henmeter' WHERE `name`="elevation";
UPDATE `runalyze_dataset` SET `label` = 'Kalorien' WHERE `name`="kcal";
UPDATE `runalyze_dataset` SET `label` = 'durchschn. Puls' WHERE `name`="pulse_avg";
UPDATE `runalyze_dataset` SET `label` = 'max. Puls' WHERE `name`="pulse_max";
UPDATE `runalyze_dataset` SET `label` = 'TRIMP' WHERE `name`="trimp";
UPDATE `runalyze_dataset` SET `label` = 'Temperatur' WHERE `name`="temperature";
UPDATE `runalyze_dataset` SET `label` = 'Wetter' WHERE `name`="weatherid";
UPDATE `runalyze_dataset` SET `label` = 'Strecke' WHERE `name`="route";
UPDATE `runalyze_dataset` SET `label` = 'Kleidung' WHERE `name`="clothes";
UPDATE `runalyze_dataset` SET `label` = 'Zwischenzeiten' WHERE `name`="splits";
UPDATE `runalyze_dataset` SET `label` = 'Bemerkung' WHERE `name`="comment";
UPDATE `runalyze_dataset` SET `label` = 'Schuh' WHERE `name`="shoeid";
UPDATE `runalyze_dataset` SET `label` = 'VDOT' WHERE `name`="vdot";
UPDATE `runalyze_dataset` SET `label` = 'Trainingspartner' WHERE `name`="partner";
UPDATE `runalyze_dataset` SET `label` = 'Lauf-ABC' WHERE `name`="abc";