<?php

namespace Runalyze\Model\WeatherCache;

/**
 * Generated by hand
 */
class EntityTest extends \PHPUnit_Framework_TestCase {

	public function testSimpleObject() {
		$WeatherCache = new Entity(array(
			Entity::TIME => '1462289507',
			Entity::GEOHASH => 'u1xjn',
			Entity::TEMPERATURE => '10',
			Entity::WINDSPEED => '25',
			Entity::WINDDEG => '302',
			Entity::HUMIDITY => '86',
			Entity::PRESSURE => '1033',
			Entity::WEATHERID => '5',
			Entity::WEATHER_SOURCE => '1'
		));

		$this->assertEquals(1462289507, $WeatherCache->time());
		$this->assertEquals('u1xjn', $WeatherCache->geohash());
		$this->assertEquals(10, $WeatherCache->temperature());
		$this->assertEquals(25, $WeatherCache->windSpeed());
		$this->assertEquals(302, $WeatherCache->windDegree());
		$this->assertEquals(86, $WeatherCache->humidity());
		$this->assertEquals(1033, $WeatherCache->pressure());
		$this->assertEquals(5, $WeatherCache->weatherid());
		$this->assertEquals(1, $WeatherCache->weatherSource());
	}

}
