<?php

namespace Runalyze\Model\Activity\Splits;

/**
 * Generated by hand
 */
class SplitTest extends \PHPUnit_Framework_TestCase {

	public function testStringConstructor() {
		$Split = new Split('R1.00|4:20');

		$this->assertEquals(1.00, $Split->distance());
		$this->assertEquals(260, $Split->time());
		$this->assertFalse($Split->isActive());
	}

	public function testParameterConstructor() {
		$Split = new Split(1.00, 260, false);

		$this->assertEquals(1.00, $Split->distance());
		$this->assertEquals(260, $Split->time());
		$this->assertFalse($Split->isActive());
	}

	public function testSetter() {
		$Split = new Split();

		$this->assertTrue($Split->isEmpty());
		$this->assertTrue($Split->isActive());

		$Split->setDistance(1.00);
		$Split->setTime(300);
		$Split->setResting();

		$this->assertFalse($Split->isEmpty());
		$this->assertEquals(1.00, $Split->distance());
		$this->assertEquals(300, $Split->time());
		$this->assertFalse($Split->isActive());
	}

}
