<?php

namespace Runalyze;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-10-10 at 21:30:18.
 */
class AthleteTest extends \PHPUnit_Framework_TestCase {
	protected function testEmpty() {
		$Athlete = new Athlete();

		$this->assertFalse( $Athlete->knowsGender() );
		$this->assertFalse( $Athlete->knowsMaximalHeartRate() );
		$this->assertFalse( $Athlete->knowsRestingHeartRate() );
		$this->assertFalse( $Athlete->knowsAge() );
		$this->assertFalse( $Athlete->knowsWeight() );
	}

	public function testGenderAndHRmax() {
		$Gender = new \Gender();
		$Gender->set( \Gender::MALE );

		$Athlete = new Athlete($Gender, 210);

		$this->assertTrue( $Athlete->knowsGender() );
		$this->assertTrue( $Athlete->knowsMaximalHeartRate() );
		$this->assertFalse( $Athlete->knowsRestingHeartRate() );
		$this->assertFalse( $Athlete->knowsAge() );
		$this->assertFalse( $Athlete->knowsWeight() );

		$this->assertEquals( $Gender, $Athlete->gender() );
		$this->assertEquals( 210, $Athlete->maximalHR() );
	}

	public function testAllProperties() {
		$Gender = new \Gender();
		$Gender->set( \Gender::MALE );

		$Athlete = new Athlete($Gender, 210, 45, 70, 25);

		$this->assertTrue( $Athlete->knowsGender() );
		$this->assertTrue( $Athlete->knowsMaximalHeartRate() );
		$this->assertTrue( $Athlete->knowsRestingHeartRate() );
		$this->assertTrue( $Athlete->knowsAge() );
		$this->assertTrue( $Athlete->knowsWeight() );

		$this->assertEquals( $Gender, $Athlete->gender() );
		$this->assertEquals( 210, $Athlete->maximalHR() );
		$this->assertEquals( 45, $Athlete->restingHR() );
		$this->assertEquals( 70, $Athlete->weight() );
		$this->assertEquals( 25, $Athlete->age() );
	}

}
