<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-10 at 17:21:17.
 */
class ImporterFiletypeFITLOGTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ImporterFiletypeFITLOG
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ImporterFiletypeFITLOG;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() { }

	/**
	 * Test: empty string
	 */
	public function testEmptyString() {
		$this->object->parseString('');

		$this->assertTrue( $this->object->failed() );
		$this->assertEmpty( $this->object->objects() );
		$this->assertNotEmpty( $this->object->getErrors() );
	}

	/**
	 * Test: incorrect xml-file 
	 */
	public function test_notFITLOG() {
		$this->object->parseString('<any><xml><file></file></xml></any>');

		$this->assertTrue( $this->object->failed() );
		$this->assertEmpty( $this->object->objects() );
		$this->assertNotEmpty( $this->object->getErrors() );
	}

	/**
	 * Test: incorrect xml-file 
	 */
	public function test_noTrack() {
		$this->object->parseString('<?xml version="1.0"?>
<FitnessWorkbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.zonefivesoftware.com/xmlschemas/FitnessLogbook/v2">
  <AthleteLog>
    <Athlete Name="Michael Pohl"/>
    <Activity StartTime="2013-12-10T00:00:00+01:00">
      <Duration TotalSeconds="2420"/>
      <Distance TotalMeters="10000"/>
      <Calories TotalCal="565"/>
      <Category Name="Laufen"/>
      <Location Name=""/>
    </Activity>
  </AthleteLog>
</FitnessWorkbook>');

		$this->assertFalse( $this->object->failed() );
		$this->assertNotEmpty( $this->object->objects() );
		$this->assertEmpty( $this->object->getErrors() );
	}

	/**
	 * Test: standard file
	 * Filename: "20110411_Laufeinheit_division_by_zero.fitlog" 
	 */
	public function test_standard() {
		$this->object->parseFile('../tests/testfiles/sporttracks/20110411_Laufeinheit_division_by_zero.fitlog');

		$this->assertEquals( array(), $this->object->getErrors() );
		$this->assertFalse( $this->object->hasMultipleTrainings() );
		$this->assertFalse( $this->object->failed() );

		$this->assertEquals( 1399, $this->object->object()->getTimeInSeconds(), '', 30);
		$this->assertEquals( 4.09, $this->object->object()->getDistance(), '', 0.1);
		$this->assertEquals( 361, $this->object->object()->getCalories(), '', 10);
		$this->assertEquals( 161, $this->object->object()->getPulseAvg(), '', 2);
		$this->assertEquals( 176, $this->object->object()->getPulseMax(), '', 2);

		$this->assertFalse( $this->object->object()->Splits()->areEmpty() );
		$this->assertEquals(
			"0.002|0:00-1.000|5:31-1.000|5:40-1.000|5:55-1.000|5:32-0.087|0:39",
			$this->object->object(2)->Splits()->asString()
		);
	}

	/**
	 * Test: "spinning.fitlog"
	 */
	public function testIndoorSpinning() {
		$this->object->parseFile('../tests/testfiles/sporttracks/spinning.fitlog');

		$this->assertFalse($this->object->hasMultipleTrainings());
		$this->assertFalse($this->object->failed());

		$this->assertEquals(1803, $this->object->object()->getTimeInSeconds());
		$this->assertEquals(0.0, $this->object->object()->getDistance());
		$this->assertEquals(108, $this->object->object()->getPulseAvg());
		$this->assertEquals(144, $this->object->object()->getPulseMax());

		$this->assertTrue($this->object->object()->hasArrayTime());
		$this->assertTrue($this->object->object()->hasArrayHeartrate());
	}

}
