<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-05 at 12:10:12.
 */
class ConfigurationValueSelectTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ConfigurationValueSelect
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ConfigurationValueSelect('key', array(
			'default' => 'one',
			'options' => array(
				'one' => 'Option one',
				'two' => 'Option two'
			)
		));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ConfigurationValueSelect::set
	 */
	public function testSet() {
		$this->assertEquals('one', $this->object->value());
		$this->assertEquals('one', $this->object->valueAsString());

		$this->object->set('two');
		$this->assertEquals('two', $this->object->value());
		$this->assertEquals('two', $this->object->valueAsString());
	}

	/**
	 * @expectedException InvalidArgumentException
	 */
	public function testInvalidOption() {
		$this->object->set('three');
	}

}
