<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-04 at 23:01:54.
 */
class ConfigurationValueBoolTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ConfigurationValueBool
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ConfigurationValueBool('key', array('default' => false));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ConfigurationValue::set
	 * @covers ConfigurationValue::setFromString
	 * @covers ConfigurationValue::value
	 * @covers ConfigurationValue::valueAsString
	 */
	public function testSet() {
		$this->assertEquals(false, $this->object->value());
		$this->assertEquals('false', $this->object->valueAsString());

		$this->object->set(true);
		$this->assertEquals(true, $this->object->value());
		$this->assertEquals('true', $this->object->valueAsString());
	}

	/**
	 * @covers ConfigurationValue::value
	 * @covers ConfigurationValue::valueAsString
	 */
	public function testSetFromString() {
		$this->object->setFromString('true');
		$this->assertEquals(true, $this->object->value() );
	}

	/**
	 * @covers ConfigurationValue::setFromPost
	 */
	public function testSetFromPost() {
		$_POST['key_sent'] = 'true';

		$this->object->setFromPost();
		$this->assertEquals(false, $this->object->value());

		$_POST['key'] = 'true';

		$this->object->setFromPost();
		$this->assertEquals(true, $this->object->value());

		unset($_POST['key_sent']);
		unset($_POST['key']);
	}

}
