<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-15 at 18:49:31.
 */
class ParameterStringTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ParameterString
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ParameterString('');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ParameterString::valueAsString
	 */
	public function testAsString() {
		$this->assertEquals( '', $this->object->value() );
		$this->assertEquals( '', $this->object->valueAsString() );

		$this->object->set('foo');
		$this->assertEquals( 'foo', $this->object->value() );
		$this->assertEquals( 'foo', $this->object->valueAsString() );

		$this->object->set('bar');
		$this->assertEquals( 'bar', $this->object->value() );
		$this->assertEquals( 'bar', $this->object->valueAsString() );
	}

}
