<?php

require_once dirname(__FILE__) . '/../../../inc/import/class.ImporterCSV.php';

/**
 * Test class for ImporterCSV.
 * Generated by PHPUnit on 2012-07-05 at 11:55:44.
 */
class ImporterCSVTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ImporterCSV
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {}

	/**
	 * @covers ImporterCSV::displayHTMLformular
	 */
	public function testDisplayHTMLformular() {
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}
}

?>
