<?php

require_once dirname(__FILE__) . '/../../../inc/import/class.ImporterTCX.php';

/**
 * Test class for ImporterTCX.
 * Generated by PHPUnit on 2012-04-24 at 13:10:23.
 */
class ImporterTCXTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ImporterTCX
	 */
	protected $object;

	protected function setUp() {}
	protected function tearDown() {}

	/**
	 * @covers ImporterTCX::saveTCX
	 * @todo Implement testSaveTCX().
	 */
	public function testSaveTCX() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ImporterTCX::displayHTMLformular
	 * @todo Implement testDisplayHTMLformular().
	 */
	public function testDisplayHTMLformular() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ImporterTCX::addTCXdataToTraining
	 * @todo Implement testAddTCXdataToTraining().
	 */
	public function testAddTCXdataToTraining() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers ImporterTCX::decodeCompressedData
	 * @todo Implement testDecodeCompressedData().
	 */
	public function testDecodeCompressedData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * To be sure how ->count() works on SimpleXMLElement 
	 */
	public function testCountFunctionality() {
		$XML = simplexml_load_string_utf8('
			<root>
				<foo />
				<files>
					<file />
					<file />
					<file />
					<file />
				</files>
				<bar></bar>
				<files>
					<file></file>
				</files>
				<another />
			</root>');

		// SimpleXmlElement::count() >= PHP 5.3.0
		$this->assertEquals(2, $XML->files->count());
		$this->assertEquals(4, $XML->files->file->count());
		$this->assertEquals(4, $XML->files[0]->file->count());
		$this->assertEquals(1, $XML->files[1]->file->count());

		// count() < PHP 5.3.0
		$this->assertEquals(2, count($XML->files));
		$this->assertEquals(4, count($XML->files->file));
		$this->assertEquals(4, count($XML->files[0]->file));
		$this->assertEquals(1, count($XML->files[1]->file));
	}
}

?>
