<?php

namespace Runalyze\Model\Route;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-11-10 at 18:38:24.
 */
class LoopTest extends \PHPUnit_Framework_TestCase {

	public function testRouteLoop() {
		$Loop = new Loop(new Object(array(
			Object::GEOHASHES => array('u1xjhxf507s1', 'u1xjhxf6b7s9', 'u1xjhxfd8jyw', 'u1xjhxfdx0cw', 'u1xjhxffrhw4')
		)));

		$Loop->nextStep();
		$this->assertEquals('u1xjhxf6b7s9', $Loop->geohash());
		$this->assertEquals(13.41, $Loop->calculatedStepDistance(), '', 0.2);

		$Loop->setStepSize(2);
		$Loop->nextStep();
		$this->assertEquals('u1xjhxfdx0cw', $Loop->geohash());
		$this->assertEquals(0.0, $Loop->calculatedStepDistance());

		$Loop->nextStep();
		$this->assertTrue($Loop->isAtEnd());
	}

}
