<?php

namespace Runalyze\Plugin\Statistic\Races;

require_once FRONTEND_PATH.'../plugin/RunalyzePluginStat_Wettkampf/RaceContainer.php';

use DB;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2015-02-01 at 21:12:40.
 */
class RaceContainerTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var RaceContainer
	 */
	protected $Container;

	/**
	 * @var \PDO
	 */
	protected $PDO;

	/**
	 * @var int
	 */
	const RACEID = 5;

	protected function setUp() {
		$this->PDO = DB::getInstance();
		$this->PDO->exec('DELETE FROM `runalyze_training`');

		$this->Container = new RaceContainer($this->PDO, self::RACEID);
	}

	protected function tearDown() {
		$this->PDO->exec('DELETE FROM `runalyze_training`');
	}

	protected function insert($distance, $s = 0, $time = 0) {
		$this->PDO->exec('INSERT INTO `runalyze_training` (`distance`, `s`, `time`, `typeid`, `accountid`) VALUES ("'.$distance.'", "'.$s.'", "'.$time.'", "'.self::RACEID.'", 0)');
	}

	public function testGeneralFunctionality() {
		$this->insert( 1.0,  3*60 +  0);
		$this->insert( 3.0, 10*60 +  0);
		$this->insert( 3.0, 10*60 + 27);
		$this->insert( 5.0, 17*60 + 52);
		$this->insert( 5.0, 18*60 + 13);
		$this->insert( 5.1, 19*60 +  0);
		$this->insert(21.1, 1*60*60 + 19*60 +  0);

		$this->Container->fetchData();

		$this->assertEquals(7, $this->Container->num());
		$this->assertEquals(array('1', '3', '5', '5.1', '21.1'), $this->Container->distances());

		$Races1k = $this->Container->races( 1.0);
		$Races3k = $this->Container->races( 3.0);
		$Races5k = $this->Container->races( 5.0);
		$Races51 = $this->Container->races( 5.1);
		$RacesHM = $this->Container->races(21.1);

		$this->assertEquals(1, count($Races1k));
		$this->assertEquals(2, count($Races3k));
		$this->assertEquals(2, count($Races5k));
		$this->assertEquals(1, count($Races51));
		$this->assertEquals(1, count($RacesHM));

		$this->assertEquals(10*60 +  0, $Races3k[0]['s']);
		$this->assertEquals(10*60 + 27, $Races3k[1]['s']);
	}

}
