<?php
$PLUGINMAP = array(
'RunalyzePluginPanel_Sportler' => '../plugin/RunalyzePluginPanel_Sportler/class.RunalyzePluginPanel_Sportler.php',
'RunalyzePluginStat_Laufabc' => '../plugin/RunalyzePluginStat_Laufabc/class.RunalyzePluginStat_Laufabc.php',
'RunalyzePluginTool_DbBackup' => '../plugin/RunalyzePluginTool_DbBackup/class.RunalyzePluginTool_DbBackup.php',
'RunalyzePluginPanel_Ziele' => '../plugin/RunalyzePluginPanel_Ziele/class.RunalyzePluginPanel_Ziele.php',
'RunalyzePluginTool_AnalyzeVDOT' => '../plugin/RunalyzePluginTool_AnalyzeVDOT/class.RunalyzePluginTool_AnalyzeVDOT.php',
'RunalyzePluginStat_Wetter' => '../plugin/RunalyzePluginStat_Wetter/class.RunalyzePluginStat_Wetter.php',
'RunalyzePluginStat_Rekorde' => '../plugin/RunalyzePluginStat_Rekorde/class.RunalyzePluginStat_Rekorde.php',
'RunalyzePluginStat_Strecken' => '../plugin/RunalyzePluginStat_Strecken/class.RunalyzePluginStat_Strecken.php',
'RunalyzePluginStat_Statistiken' => '../plugin/RunalyzePluginStat_Statistiken/class.RunalyzePluginStat_Statistiken.php',
'RunalyzePluginStat_Wettkampf' => '../plugin/RunalyzePluginStat_Wettkampf/class.RunalyzePluginStat_Wettkampf.php',
'RunalyzePluginStat_Trainingszeiten' => '../plugin/RunalyzePluginStat_Trainingszeiten/class.RunalyzePluginStat_Trainingszeiten.php',
'RunalyzePluginStat_Trainingspartner' => '../plugin/RunalyzePluginStat_Trainingspartner/class.RunalyzePluginStat_Trainingspartner.php',
'RunalyzePluginTool_JDTables' => '../plugin/RunalyzePluginTool_JDTables/class.RunalyzePluginTool_JDTables.php',
'RunalyzePluginStat_Analyse' => '../plugin/RunalyzePluginStat_Analyse/class.RunalyzePluginStat_Analyse.php',
'RunalyzePluginStat_Hoehenmeter' => '../plugin/RunalyzePluginStat_Hoehenmeter/class.RunalyzePluginStat_Hoehenmeter.php',
'RunalyzePluginTool_MultiEditor' => '../plugin/RunalyzePluginTool_MultiEditor/class.RunalyzePluginTool_MultiEditor.php',
'RunalyzePluginTool_DatenbankCleanup' => '../plugin/RunalyzePluginTool_DatenbankCleanup/class.RunalyzePluginTool_DatenbankCleanup.php',
'RunalyzePluginPanel_Sports' => '../plugin/RunalyzePluginPanel_Sports/class.RunalyzePluginPanel_Sports.php',
'RunalyzePluginPanel_Rechenspiele' => '../plugin/RunalyzePluginPanel_Rechenspiele/class.RunalyzePluginPanel_Rechenspiele.php',
'RunalyzePluginPanel_Schuhe' => '../plugin/RunalyzePluginPanel_Schuhe/class.RunalyzePluginPanel_Schuhe.php',
'RunalyzePluginPanel_Prognose' => '../plugin/RunalyzePluginPanel_Prognose/class.RunalyzePluginPanel_Prognose.php',
'RunalyzePluginTool_Cacheclean' => '../plugin/RunalyzePluginTool_Cacheclean/class.RunalyzePluginTool_Cacheclean.php',
);