<?php

namespace Runalyze\Calculation\Distribution;

class Distribution_MockTester extends Distribution {
	public function histogram() {
		return array(
			10 => 1,
			15 => 2,
			20 => 1
		);
	}
}

class Distribution_MockTester2 extends Distribution {
	public function histogram() {
		return array(
			0 => 5,
			80 => 10,
			85 => 10,
			90 => 15
		);
	}
}

/**
 * Generated by hand
 */
class DistributionTest extends \PHPUnit_Framework_TestCase {

	public function testMock() {
		$Dist = new Distribution_MockTester();

		$this->assertEquals( array(
			10 => 1,
			15 => 2,
			20 => 1
		), $Dist->histogram() );

		$Dist->calculateStatistic();

		$this->assertEquals( 10, $Dist->min() );
		$this->assertEquals( 15, $Dist->mean() );
		$this->assertEquals( 15, $Dist->median() );
		$this->assertEquals( 15, $Dist->mode() );
		$this->assertEquals( 20, $Dist->max() );
		$this->assertEquals( 12.5, $Dist->variance() );
		$this->assertEquals( 3.5, $Dist->stdDev(), '', 0.1 );
	}

	public function testMock2() {
		$Dist = new Distribution_MockTester2();

		$Dist->calculateStatistic();

		$this->assertEquals( 0, $Dist->min() );
		$this->assertEquals( 75, $Dist->mean() );
		$this->assertEquals( 85, $Dist->median() );
		$this->assertEquals( 90, $Dist->mode() );
		$this->assertEquals( 90, $Dist->max() );
		$this->assertEquals( 818.75, $Dist->variance() );
		$this->assertEquals( 28.6, $Dist->stdDev(), '', 0.1 );
	}

}
