<?php

namespace Runalyze\Calculation\Distribution;

/**
 * Generated by hand
 */
class EmpiricalTest extends \PHPUnit_Framework_TestCase {

	public function testSimpleArray() {
		$Dist = new Empirical(array(
			10,
			15, 15,
			20
		));

		$this->assertEquals( array(
			10 => 1,
			15 => 2,
			20 => 1
		), $Dist->histogram() );
	}

}
