<?php

namespace Runalyze\Calculation\Distribution;

use Runalyze\Model\Trackdata;

/**
 * Generated by hand
 */
class TimeSeriesForTrackdataTest extends \PHPUnit_Framework_TestCase {

	public function testSimpleArray() {
		$Dist = new TimeSeriesForTrackdata(
			new Trackdata\Object(array(
				Trackdata\Object::TIME => array(30, 60, 90, 120, 150, 180, 210, 240, 270, 300),
				Trackdata\Object::HEARTRATE => array(120, 120, 150, 150, 150, 180, 150, 180, 150, 120),
				Trackdata\Object::DISTANCE => array(0.1, 0.2, 0.35, 0.50, 0.65, 0.85, 1.0, 1.2, 1.35, 1.45),
				Trackdata\Object::CADENCE => array(80, 84, 85, 90, 95, 100, 95, 100, 95, 85),
				Trackdata\Object::GROUNDCONTACT => array(200, 185, 170, 160, 150, 120, 200, 120, 200, 200),
			)),
			Trackdata\Object::HEARTRATE,
			array(Trackdata\Object::DISTANCE),
			array(Trackdata\Object::CADENCE, Trackdata\Object::GROUNDCONTACT)
		);

		$this->assertEquals( array(
			120 => 90,
			150 => 150,
			180 => 60
		), $Dist->histogram() );

		$this->assertEquals( array(
			120 => array(
				Trackdata\Object::DISTANCE => 0.3,
				Trackdata\Object::CADENCE => 83,
				Trackdata\Object::GROUNDCONTACT => 195
			),
			150 => array(
				Trackdata\Object::DISTANCE => 0.75,
				Trackdata\Object::CADENCE => 92,
				Trackdata\Object::GROUNDCONTACT => 176
			),
			180 => array(
				Trackdata\Object::DISTANCE => 0.4,
				Trackdata\Object::CADENCE => 100,
				Trackdata\Object::GROUNDCONTACT => 120
			)
		), $Dist->data() );
	}

	/**
	 * @expectedException \InvalidArgumentException
	 */
	public function testException() {
		new TimeSeriesForTrackdata(
			new Trackdata\Object(array(
				Trackdata\Object::TIME => array(30, 60, 90, 120, 150, 180, 210, 240, 270, 300),
				Trackdata\Object::HEARTRATE => array(120, 120, 150, 150, 150, 180, 150, 180, 150, 120)
			)),
			Trackdata\Object::HEARTRATE,
			array(Trackdata\Object::DISTANCE)
		);
	}

}
