<?php

namespace Runalyze\Data\Elevation\Calculation;

/**
 * Generated by hand
 */
class ReumannWitkamTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @expectedException \RuntimeException
	 */
	public function testSimpleArray() {
		// This algorithm ist not implemented
		$DP = new ReumannWitkam(array(0, 2, 4, 6, 5, 7, 4, 8, 10, 0), 0);
		$DP->runSmoothing();
	}

}
