<?php

namespace Runalyze\Activity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2015-06-06 at 13:59:56.
 */
class StrideLengthTest extends \PHPUnit_Framework_TestCase {

	public function testStaticFunction() {
		$this->assertEquals('1.23&nbsp;m', StrideLength::format(123));
	}

	public function testInMeter() {
		$StrideLength = new StrideLength(107);

		$this->assertEquals(1.07, $StrideLength->inM());
		$this->assertEquals('1.07&nbsp;m', $StrideLength->asM());
	}

	public function testInCentimeter() {
		$StrideLength = new StrideLength(87);

		$this->assertEquals(87, $StrideLength->inCM());
		$this->assertEquals('87&nbsp;cm', $StrideLength->asCM());
	}

	public function testInvalidValues() {
		$StrideLength = new StrideLength(-42);

		$this->assertEquals(0, $StrideLength->inM());
		$this->assertEquals(0, $StrideLength->inCM());
	}

}
