<?php

namespace Runalyze\Model\Swimdata;

/**
 * Generated by hand
 */
class EntityTest extends \PHPUnit_Framework_TestCase {

	protected function simpleObject() {
		return new Entity(array(
			Entity::POOL_LENGTH => 2500,
			Entity::STROKE => array(25, 20, 15, 20),
			Entity::STROKETYPE => array(2, 2, 2, 2)
		));
	}

	public function testEmptyObject() {
		$T = new Entity();

		$this->assertFalse($T->has(Entity::STROKE));
		$this->assertFalse($T->has(Entity::STROKETYPE));
		$this->assertFalse($T->has(Entity::SWOLF));
		$this->assertFalse($T->has(Entity::SWOLFCYCLES));
	}

	public function testSimpleObject() {
		$T = $this->simpleObject();

		$this->assertEquals(2500, $T->poollength());
		$this->assertEquals(array(25, 20, 15, 20), $T->stroke());
		$this->assertEquals(array(2, 2, 2, 2), $T->stroketype());
		$this->assertEquals(array(), $T->swolf());
		$this->assertEquals(array(), $T->swolfcycles());
	}

}
