<?php

namespace Runalyze\Model\Swimdata;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-11-10 at 18:38:24.
 */
class LoopTest extends \PHPUnit_Framework_TestCase {

	public function testSwimdataLoop() {
		$Loop = new Loop(new Object(array(
			Object::STROKE => array(25, 20, 15, 20),
			Object::STROKETYPE => array(2, 2, 2, 2)
		)));

		$Loop->nextStep();
		$this->assertEquals(20, $Loop->stroke());
		$this->assertEquals(2, $Loop->stroketype());

		$Loop->setStepSize(2);
		$Loop->nextStep();
		$this->assertEquals(20, $Loop->stroke());
		$this->assertEquals(2, $Loop->stroketype());

		$Loop->nextStep();
		$this->assertTrue($Loop->isAtEnd());
	}

}
