<?php

namespace Runalyze\Model\Swimdata;

/**
 * Generated by hand
 */
class ObjectTest extends \PHPUnit_Framework_TestCase {

	protected function simpleObject() {
		return new Object(array(
			Object::POOL_LENGTH => 2500,
			Object::STROKE => array(25, 20, 15, 20),
			Object::STROKETYPE => array(2, 2, 2, 2)
		));
	}

	public function testEmptyObject() {
		$T = new Object();

		$this->assertFalse($T->has(Object::STROKE));
		$this->assertFalse($T->has(Object::STROKETYPE));
		$this->assertFalse($T->has(Object::SWOLF));
		$this->assertFalse($T->has(Object::SWOLFCYCLES));
	}

	public function testSimpleObject() {
		$T = $this->simpleObject();

		$this->assertEquals(2500, $T->poollength());
		$this->assertEquals(array(25, 20, 15, 20), $T->stroke());
		$this->assertEquals(array(2, 2, 2, 2), $T->stroketype());
		$this->assertEquals(array(), $T->swolf());
		$this->assertEquals(array(), $T->swolfcycles());
	}

}
