<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-09 at 16:01:40.
 */
class ActivityRouteBreakTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ActivityRouteBreak
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ActivityRouteBreak('key');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ActivityRouteBreak::never
	 */
	public function testNever() {
		$this->assertFalse( $this->object->never() );
		$this->object->set( ActivityRouteBreak::NO_BREAK );
		$this->assertTrue( $this->object->never() );
	}

}
