<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-09 at 15:32:13.
 */
class ActivityPlotModeTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ActivityPlotMode
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ActivityPlotMode('key');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ActivityPlotMode::showSeperated
	 * @covers ActivityPlotMode::showPaceAndHR
	 * @covers ActivityPlotMode::showCollection
	 */
	public function testShowCollection() {
		$this->assertTrue( $this->object->showSeperated() );
		$this->assertFalse( $this->object->showPaceAndHR() );
		$this->assertFalse( $this->object->showCollection() );

		$this->object->set( ActivityPlotMode::PACE_HR );
		$this->assertFalse( $this->object->showSeperated() );
		$this->assertTrue( $this->object->showPaceAndHR() );
		$this->assertFalse( $this->object->showCollection() );

		$this->object->set( ActivityPlotMode::PACE_HR_ELEVATION );
		$this->assertFalse( $this->object->showSeperated() );
		$this->assertFalse( $this->object->showPaceAndHR() );
		$this->assertTrue( $this->object->showCollection() );
	}

}
