<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2014-09-09 at 16:02:54.
 */
class ActivityPlotPrecisionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ActivityPlotPrecision
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ActivityPlotPrecision('key');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers ActivityPlotPrecision::byDistance
	 * @covers ActivityPlotPrecision::distanceStep
	 * @covers ActivityPlotPrecision::byPoints
	 * @covers ActivityPlotPrecision::numberOfPoints
	 */
	public function testAssigns() {
		$this->object->set('100m');
		$this->assertTrue( $this->object->byDistance() );
		$this->assertFalse( $this->object->byPoints() );
		$this->assertEquals( 100, $this->object->distanceStep() );

		$this->object->set('200points');
		$this->assertFalse( $this->object->byDistance() );
		$this->assertTrue( $this->object->byPoints() );
		$this->assertEquals( 200, $this->object->numberOfPoints() );
	}

}
